import json, re

B = {
"it": dict(
 site=dict(gateKicker="Benvenuto da Kalamà", gateTitle="Dove sei, a Málaga o a Malta?", gateSub="Scegli la tua città: ti mostriamo carta, orari e come arrivare al tuo Kalamà.", choose="Scegli", malagaTag="Spagna · Soho", maltaTag="Malta · Seafront", change="Cambia sede", yourKalama="Il tuo Kalamà", directions="Come arrivare", bookTable="Richiedi un tavolo", delivery="Consegna a domicilio", orderTakeaway="Ordina da asporto", talkTeam="Parla con il team", call="Chiama", heroSub=dict(malaga="Il mare d'Italia, appena fatto nel Soho di Málaga: fritti leggeri, pasta fresca e panini di mare da gustare qui, da asporto o a domicilio.", malta="Il mare di Sliema, fritto al momento: pesce fresco, fritti leggeri e anima italiana sul lungomare, da gustare qui o da portare via.")),
 booking=dict(title="Richiedi un tavolo", steps=["Quando", "Tavolo", "I tuoi dati", "Riepilogo"], date="Data", lunch="Pranzo", dinner="Cena", closed="Chiuso in questa data: scegli un altro giorno.", guests="Coperti", zone="Preferenza di zona", zones=dict(any="Nessuna preferenza", indoor="Interno", outdoor="Esterno"), occasion="L'occasione", occasions=dict(couple="In coppia", friends="Con amici", family="In famiglia", celebration="Celebrazione", group="Gruppo"), accessibility="Ci serve un accesso agevolato", tableIntro="Raccontaci come sarà il tavolo.", who="Chi fa la richiesta?", name="Nome della prenotazione", email="Email", phone="Telefono (opzionale)", notes="Allergie o dettagli importanti (opzionale)", review="Controlla e invia", submit="Invia richiesta", sending="Invio...", next="Avanti", back="Indietro", successTitle="Richiesta inviata!", successText="Il team di {site} ti risponderà via email o WhatsApp. Vuoi accelerare? Inviaci la richiesta anche su WhatsApp.", openWhatsapp="Invia su WhatsApp", close="Chiudi", people="persone", note="Non è una prenotazione confermata: riceverai risposta dal ristorante.", error="Invio non riuscito, riprova o scrivici su WhatsApp."),
 chat=dict(title="Kalamà ti aiuta", subtitle="Assistente di Kalamà", hello="Ciao! Sono l'assistente di {site}: posso aiutarti con menù, orari, ordini, indicazioni o una richiesta di tavolo.", placeholder="Scrivi ciò di cui hai bisogno...", quick=dict(menu="Vedi menu", book="Richiedi tavolo", team="Parla con il team", directions="Come arrivare"), error="Ops, non riesco a rispondere ora. Scrivici su WhatsApp!", open="Apri l'assistente"),
 cookie=dict(text="La tua privacy, senza sorprese: salviamo solo sede, lingua e preferenze sul tuo dispositivo. Nessun cookie pubblicitario.", accept="Accetta e continua"),
),
"en": dict(
 site=dict(gateKicker="Welcome to Kalamà", gateTitle="Where are you, Málaga or Malta?", gateSub="Pick your city: we'll show you the menu, hours and how to reach your Kalamà.", choose="Choose", malagaTag="Spain · Soho", maltaTag="Malta · Seafront", change="Change location", yourKalama="Your Kalamà", directions="Directions", bookTable="Request a table", delivery="Home delivery", orderTakeaway="Order takeaway", talkTeam="Talk to the team", call="Call", heroSub=dict(malaga="Italy's sea, freshly made in Málaga's Soho: light fried fish, fresh pasta and seafood sandwiches to eat here, take away or get delivered.", malta="Sliema's sea, fried to order: fresh fish, light fritti and Italian soul on the seafront, to enjoy here or take away.")),
 booking=dict(title="Request a table", steps=["When", "Table", "Your details", "Review"], date="Date", lunch="Lunch", dinner="Dinner", closed="Closed on this date: please pick another day.", guests="Guests", zone="Seating preference", zones=dict(any="No preference", indoor="Indoor", outdoor="Outdoor"), occasion="The occasion", occasions=dict(couple="As a couple", friends="With friends", family="With family", celebration="Celebration", group="Group"), accessibility="We need easy access", tableIntro="Tell us about your table.", who="Who is requesting?", name="Name for the booking", email="Email", phone="Phone (optional)", notes="Allergies or important details (optional)", review="Check and send", submit="Send request", sending="Sending...", next="Next", back="Back", successTitle="Request sent!", successText="The {site} team will reply by email or WhatsApp. Want to speed it up? Send us the request on WhatsApp too.", openWhatsapp="Send on WhatsApp", close="Close", people="people", note="This is not a confirmed booking: the restaurant will get back to you.", error="Sending failed, try again or message us on WhatsApp."),
 chat=dict(title="Kalamà helps you", subtitle="Kalamà assistant", hello="Hi! I'm the {site} assistant: I can help with the menu, hours, orders, directions or a table request.", placeholder="Type what you need...", quick=dict(menu="See menu", book="Request table", team="Talk to the team", directions="Directions"), error="Oops, I can't answer right now. Message us on WhatsApp!", open="Open the assistant"),
 cookie=dict(text="Your privacy, no surprises: we only store your location, language and preferences on your device. No advertising cookies.", accept="Accept and continue"),
),
"es": dict(
 site=dict(gateKicker="Bienvenido a Kalamà", gateTitle="¿Dónde estás, en Málaga o en Malta?", gateSub="Elige tu ciudad y te mostramos la carta, los horarios y cómo llegar a tu Kalamà.", choose="Elegir", malagaTag="España · Soho", maltaTag="Malta · Seafront", change="Cambiar sede", yourKalama="Tu Kalamà", directions="Cómo llegar", bookTable="Solicitar mesa", delivery="Entrega a domicilio", orderTakeaway="Pedir para llevar", talkTeam="Hablar con el equipo", call="Llamar", heroSub=dict(malaga="El mar de Italia, recién hecho en el Soho de Málaga: fritura ligera, pasta fresca y bocadillos de mar para comer aquí, llevar o pedir a domicilio.", malta="El mar de Sliema, frito al momento: pescado fresco, fritura ligera y alma italiana en el paseo marítimo, para comer aquí o llevar.")),
 booking=dict(title="Solicitar mesa", steps=["Cuándo", "Mesa", "Tus datos", "Revisar"], date="Fecha", lunch="Almuerzo", dinner="Cena", closed="Cerrado en esta fecha: elige otro día.", guests="Comensales", zone="Preferencia de zona", zones=dict(any="Sin preferencia", indoor="Interior", outdoor="Terraza"), occasion="El plan", occasions=dict(couple="En pareja", friends="Con amigos", family="En familia", celebration="Celebración", group="Comida de grupo"), accessibility="Necesitamos acceso cómodo", tableIntro="Cuéntanos cómo será la mesa.", who="¿Quién hace la solicitud?", name="Nombre de la reserva", email="Correo electrónico", phone="Teléfono (opcional)", notes="Alergias o detalles importantes (opcional)", review="Revisa y envía", submit="Enviar solicitud", sending="Enviando...", next="Siguiente", back="Atrás", successTitle="¡Solicitud enviada!", successText="El equipo de {site} te responderá por email o WhatsApp. ¿Quieres acelerar? Envíanos la solicitud también por WhatsApp.", openWhatsapp="Enviar por WhatsApp", close="Cerrar", people="personas", note="No es una reserva confirmada: el restaurante te responderá.", error="No se pudo enviar, inténtalo de nuevo o escríbenos por WhatsApp."),
 chat=dict(title="Kalamà te ayuda", subtitle="Asistente de Kalamà", hello="¡Hola! Soy el asistente de {site}: puedo ayudarte con la carta, los horarios, pedidos, cómo llegar o una solicitud de mesa.", placeholder="Escribe lo que necesitas...", quick=dict(menu="Ver carta", book="Solicitar mesa", team="Hablar con el equipo", directions="Cómo llegar"), error="Ups, ahora no puedo responder. ¡Escríbenos por WhatsApp!", open="Abrir el asistente"),
 cookie=dict(text="Tu privacidad, sin sorpresas: solo guardamos tu sede, idioma y preferencias en tu dispositivo. Sin cookies publicitarias.", accept="Aceptar y continuar"),
),
"de": dict(
 site=dict(gateKicker="Willkommen bei Kalamà", gateTitle="Wo bist du, in Málaga oder auf Malta?", gateSub="Wähle deine Stadt: wir zeigen dir Karte, Öffnungszeiten und den Weg zu deinem Kalamà.", choose="Wählen", malagaTag="Spanien · Soho", maltaTag="Malta · Seafront", change="Standort wechseln", yourKalama="Dein Kalamà", directions="Anfahrt", bookTable="Tisch anfragen", delivery="Lieferung nach Hause", orderTakeaway="Zum Mitnehmen bestellen", talkTeam="Mit dem Team sprechen", call="Anrufen", heroSub=dict(malaga="Italiens Meer, frisch zubereitet im Soho von Málaga: leicht Frittiertes, frische Pasta und Fisch-Sandwiches – hier, zum Mitnehmen oder geliefert.", malta="Das Meer von Sliema, frisch frittiert: frischer Fisch, leichte Fritti und italienische Seele an der Promenade – hier oder zum Mitnehmen.")),
 booking=dict(title="Tisch anfragen", steps=["Wann", "Tisch", "Deine Daten", "Prüfen"], date="Datum", lunch="Mittag", dinner="Abend", closed="An diesem Tag geschlossen: bitte wähle einen anderen Tag.", guests="Personen", zone="Sitzplatz-Wunsch", zones=dict(any="Keine Präferenz", indoor="Innen", outdoor="Außen"), occasion="Der Anlass", occasions=dict(couple="Zu zweit", friends="Mit Freunden", family="Mit Familie", celebration="Feier", group="Gruppe"), accessibility="Wir brauchen barrierefreien Zugang", tableIntro="Erzähl uns von deinem Tisch.", who="Wer stellt die Anfrage?", name="Name der Reservierung", email="E-Mail", phone="Telefon (optional)", notes="Allergien oder wichtige Hinweise (optional)", review="Prüfen und senden", submit="Anfrage senden", sending="Wird gesendet...", next="Weiter", back="Zurück", successTitle="Anfrage gesendet!", successText="Das Team von {site} antwortet dir per E-Mail oder WhatsApp. Schneller? Schick uns die Anfrage auch per WhatsApp.", openWhatsapp="Per WhatsApp senden", close="Schließen", people="Personen", note="Keine bestätigte Reservierung: das Restaurant meldet sich bei dir.", error="Senden fehlgeschlagen, versuch es erneut oder schreib uns per WhatsApp."),
 chat=dict(title="Kalamà hilft dir", subtitle="Kalamà-Assistent", hello="Hallo! Ich bin der Assistent von {site}: ich helfe bei Karte, Öffnungszeiten, Bestellungen, Anfahrt oder einer Tischanfrage.", placeholder="Schreib, was du brauchst...", quick=dict(menu="Karte ansehen", book="Tisch anfragen", team="Mit dem Team sprechen", directions="Anfahrt"), error="Ups, ich kann gerade nicht antworten. Schreib uns per WhatsApp!", open="Assistent öffnen"),
 cookie=dict(text="Deine Privatsphäre, ohne Überraschungen: wir speichern nur Standort, Sprache und Präferenzen auf deinem Gerät. Keine Werbe-Cookies.", accept="Akzeptieren und weiter"),
),
"fr": dict(
 site=dict(gateKicker="Bienvenue chez Kalamà", gateTitle="Où es-tu, à Málaga ou à Malte ?", gateSub="Choisis ta ville : on te montre la carte, les horaires et comment rejoindre ton Kalamà.", choose="Choisir", malagaTag="Espagne · Soho", maltaTag="Malte · Seafront", change="Changer de lieu", yourKalama="Ton Kalamà", directions="Itinéraire", bookTable="Demander une table", delivery="Livraison à domicile", orderTakeaway="Commander à emporter", talkTeam="Parler à l'équipe", call="Appeler", heroSub=dict(malaga="La mer d'Italie, tout juste préparée dans le Soho de Málaga : fritures légères, pâtes fraîches et sandwichs de la mer, sur place, à emporter ou livrés.", malta="La mer de Sliema, frite à la minute : poisson frais, fritures légères et âme italienne sur le front de mer, sur place ou à emporter.")),
 booking=dict(title="Demander une table", steps=["Quand", "Table", "Vos infos", "Vérifier"], date="Date", lunch="Déjeuner", dinner="Dîner", closed="Fermé à cette date : choisis un autre jour.", guests="Couverts", zone="Préférence de zone", zones=dict(any="Sans préférence", indoor="Intérieur", outdoor="Extérieur"), occasion="L'occasion", occasions=dict(couple="En couple", friends="Entre amis", family="En famille", celebration="Célébration", group="Groupe"), accessibility="Nous avons besoin d'un accès facile", tableIntro="Parle-nous de ta table.", who="Qui fait la demande ?", name="Nom de la réservation", email="E-mail", phone="Téléphone (optionnel)", notes="Allergies ou détails importants (optionnel)", review="Vérifier et envoyer", submit="Envoyer la demande", sending="Envoi...", next="Suivant", back="Retour", successTitle="Demande envoyée !", successText="L'équipe de {site} te répondra par e-mail ou WhatsApp. Pour aller plus vite, envoie-nous aussi la demande sur WhatsApp.", openWhatsapp="Envoyer sur WhatsApp", close="Fermer", people="personnes", note="Ce n'est pas une réservation confirmée : le restaurant te répondra.", error="Envoi impossible, réessaie ou écris-nous sur WhatsApp."),
 chat=dict(title="Kalamà t'aide", subtitle="Assistant Kalamà", hello="Salut ! Je suis l'assistant de {site} : je peux t'aider pour la carte, les horaires, les commandes, l'itinéraire ou une demande de table.", placeholder="Écris ce dont tu as besoin...", quick=dict(menu="Voir la carte", book="Demander une table", team="Parler à l'équipe", directions="Itinéraire"), error="Oups, je ne peux pas répondre pour l'instant. Écris-nous sur WhatsApp !", open="Ouvrir l'assistant"),
 cookie=dict(text="Ta vie privée, sans surprise : nous enregistrons seulement le lieu, la langue et tes préférences sur ton appareil. Aucun cookie publicitaire.", accept="Accepter et continuer"),
),
"pt": dict(
 site=dict(gateKicker="Bem-vindo ao Kalamà", gateTitle="Onde estás, em Málaga ou em Malta?", gateSub="Escolhe a tua cidade: mostramos-te a ementa, os horários e como chegar ao teu Kalamà.", choose="Escolher", malagaTag="Espanha · Soho", maltaTag="Malta · Seafront", change="Mudar de local", yourKalama="O teu Kalamà", directions="Como chegar", bookTable="Pedir uma mesa", delivery="Entrega ao domicílio", orderTakeaway="Pedir para levar", talkTeam="Falar com a equipa", call="Ligar", heroSub=dict(malaga="O mar de Itália, acabado de fazer no Soho de Málaga: fritos leves, massa fresca e sanduíches de mar para comer aqui, levar ou receber em casa.", malta="O mar de Sliema, frito na hora: peixe fresco, fritos leves e alma italiana na marginal, para comer aqui ou levar.")),
 booking=dict(title="Pedir uma mesa", steps=["Quando", "Mesa", "Os teus dados", "Rever"], date="Data", lunch="Almoço", dinner="Jantar", closed="Fechado nesta data: escolhe outro dia.", guests="Pessoas", zone="Preferência de zona", zones=dict(any="Sem preferência", indoor="Interior", outdoor="Exterior"), occasion="A ocasião", occasions=dict(couple="A dois", friends="Com amigos", family="Em família", celebration="Celebração", group="Grupo"), accessibility="Precisamos de acesso facilitado", tableIntro="Conta-nos como será a mesa.", who="Quem faz o pedido?", name="Nome da reserva", email="Email", phone="Telefone (opcional)", notes="Alergias ou detalhes importantes (opcional)", review="Rever e enviar", submit="Enviar pedido", sending="A enviar...", next="Seguinte", back="Voltar", successTitle="Pedido enviado!", successText="A equipa do {site} responde-te por email ou WhatsApp. Queres acelerar? Envia-nos o pedido também por WhatsApp.", openWhatsapp="Enviar por WhatsApp", close="Fechar", people="pessoas", note="Não é uma reserva confirmada: o restaurante vai responder-te.", error="Não foi possível enviar, tenta de novo ou escreve-nos no WhatsApp."),
 chat=dict(title="O Kalamà ajuda-te", subtitle="Assistente Kalamà", hello="Olá! Sou o assistente do {site}: posso ajudar com a ementa, horários, pedidos, direções ou um pedido de mesa.", placeholder="Escreve o que precisas...", quick=dict(menu="Ver ementa", book="Pedir mesa", team="Falar com a equipa", directions="Como chegar"), error="Ups, não consigo responder agora. Escreve-nos no WhatsApp!", open="Abrir o assistente"),
 cookie=dict(text="A tua privacidade, sem surpresas: guardamos apenas o local, o idioma e as preferências no teu dispositivo. Sem cookies publicitários.", accept="Aceitar e continuar"),
),
}

p = "/app/frontend/src/i18n.js"
src = open(p).read()
for lang, blocks in B.items():
    pos = src.index(f"  {lang}: {{")
    rv = src.index("    reviews: {", pos)
    end = src.index("\n    },", rv) + len("\n    },")
    add = "".join(f"\n    {k}: {json.dumps(v, ensure_ascii=False)}," for k, v in blocks.items())
    src = src[:end] + add + src[end:]
open(p, "w").write(src)
print("ok")
